import discord
version = "1.1.0"
prefix = "!"
normal_list = (discord.Color.red(),
                discord.Color.dark_red(),
                discord.Color.blue(),
                discord.Color.dark_blue(),
                discord.Color.teal(),
                discord.Color.dark_teal(),
                discord.Color.green(),
                discord.Color.dark_green(),
                discord.Color.purple(),
                discord.Color.dark_purple(),
                discord.Color.magenta(),
                discord.Color.dark_magenta(),
                discord.Color.gold(),
                discord.Color.dark_gold(),
                discord.Color.orange(),
                discord.Color.dark_orange()
                )
spooky_list = (0xFFA500,
               0xFF8C00,
               0xFF4500,
               0xFF6347,
               0xFF7F50,
               0xFFA07A,
               0xFFFF00,
               0xFFD700,
               0xFFDAB9,
               0x8B4513,
               0xA52A2A,
               0xA0522D,
               0xD2691E,
               0xB8860B)
New_Year = (0xFF0000,
            0xFFFF00,
            0x0000FF,
            0xFFFFFF,
            0x000080,
            0x87CEEB,
            0x00FF00,
            0xFA8072,
            0xFFC0CB,
            0xFFDAB9,
            0x00FFFF,
            0xFF00FF,
            0x6A5ACD,
            0x7B68EE,
            0xE0FFFF,
            0x00FF7F,
            0xC0C0C0)
clr = normal_list
